export interface InternalCountry {
  code: string;
  name: string;
}

export const TAX_COUNTRIES: InternalCountry[] = [
  {code: 'BGR', name: 'Bulgarien'},
  {code: 'DNK', name: 'Dänemark'},
  {code: 'DEU', name: 'Deutschland'},
  {code: 'EST', name: 'Estland'},
  {code: 'FIN', name: 'Finland'},
  {code: 'GRC', name: 'Griechenland'},
  {code: 'ITA', name: 'Italien'},
  {code: 'HRV', name: 'Kroatien'},
  {code: 'LTU', name: 'Litauen'},
  {code: 'LUX', name: 'Luxemburg'},
  {code: 'MLT', name: 'Malta'},
  {code: 'AUT', name: 'Österreich'},
  {code: 'POL', name: 'Polen'},
  {code: 'PRT', name: 'Portugal'},
  {code: 'ROU', name: 'Rumänien'},
  {code: 'SWE', name: 'Schweden'},
  {code: 'SVK', name: 'Slowakei'},
  {code: 'SVN', name: 'Slowenien'},
  {code: 'CZE', name: 'Tschechische Republik'},
  {code: 'HUN', name: 'Ungarn'},
  {code: 'CYP', name: 'Zypern'}
];

export const COUNTRIES: InternalCountry[] = [
  {code: 'AFG', name: 'Afghanistan'},
  {code: 'EGY', name: 'Ägypten'},
  {code: 'ALB', name: 'Albanien'},
  {code: 'DZA', name: 'Algerien'},
  {code: 'AND', name: 'Andorra'},
  {code: 'AGO', name: 'Angola'},
  {code: 'ATG', name: 'Antigua und Barbuda'},
  {code: 'GNQ', name: 'Äquatorialguinea'},
  {code: 'ARG', name: 'Argentinien'},
  {code: 'ARM', name: 'Armenien'},
  {code: 'AZE', name: 'Aserbaidschan'},
  {code: 'ETH', name: 'Äthiopien'},
  {code: 'AUS', name: 'Australien'},
  {code: 'BHS', name: 'Bahamas'},
  {code: 'BHR', name: 'Bahrain'},
  {code: 'BGD', name: 'Bangladesch'},
  {code: 'BRB', name: 'Barbados'},
  {code: 'BLR', name: 'Belarus'},
  {code: 'BEL', name: 'Belgien'},
  {code: 'BLZ', name: 'Belize'},
  {code: 'BEN', name: 'Benin'},
  {code: 'BTN', name: 'Bhutan'},
  {code: 'BOL', name: 'Bolivien'},
  {code: 'BIH', name: 'Bosnien und Herzegowina'},
  {code: 'BWA', name: 'Botsuana'},
  {code: 'BRA', name: 'Brasilien'},
  {code: 'BRN', name: 'Brunei'},
  {code: 'BGR', name: 'Bulgarien'},
  {code: 'BFA', name: 'Burkina Faso'},
  {code: 'BDI', name: 'Burundi'},
  {code: 'CHL', name: 'Chile'},
  {code: 'CHN', name: 'China'},
  {code: 'COK', name: 'Cookinseln'},
  {code: 'CRI', name: 'Costa Rica'},
  {code: 'CUW', name: 'Curacao'},
  {code: 'CIV', name: 'Côte d´Ivoire'},
  {code: 'DNK', name: 'Dänemark'},
  {code: 'DEU', name: 'Deutschland'},
  {code: 'DMA', name: 'Dominica'},
  {code: 'DOM', name: 'Dominikanische Republik'},
  {code: 'DJI', name: 'Dschibuti'},
  {code: 'ECU', name: 'Ecuador'},
  {code: 'SLV', name: 'El Salvador'},
  {code: 'ERI', name: 'Eritrea'},
  {code: 'EST', name: 'Estland'},
  {code: 'FJI', name: 'Fidschi'},
  {code: 'FIN', name: 'Finnland'},
  {code: 'FRA', name: 'Frankreich'},
  {code: 'GAB', name: 'Gabun'},
  {code: 'GMB', name: 'Gambia'},
  {code: 'GEO', name: 'Georgien'},
  {code: 'GHA', name: 'Ghana'},
  {code: 'GRD', name: 'Grenada'},
  {code: 'GRC', name: 'Griechenland'},
  {code: 'GTM', name: 'Guatemala'},
  {code: 'GIN', name: 'Guinea'},
  {code: 'GNB', name: 'Guinea-Bissau'},
  {code: 'HTI', name: 'Haiti'},
  {code: 'HND', name: 'Honduras'},
  {code: 'IND', name: 'Indien'},
  {code: 'IDN', name: 'Indonesien'},
  {code: 'IRQ', name: 'Irak'},
  {code: 'IRN', name: 'Iran'},
  {code: 'IRL', name: 'Irland'},
  {code: 'ISL', name: 'Island'},
  {code: 'ISR', name: 'Israel'},
  {code: 'ITA', name: 'Italien'},
  {code: 'JAM', name: 'Jamaika'},
  {code: 'JPN', name: 'Japan'},
  {code: 'YEM', name: 'Jemen'},
  {code: 'JOR', name: 'Jordanien'},
  {code: 'KHM', name: 'Kambodscha'},
  {code: 'CMR', name: 'Kamerun'},
  {code: 'CAN', name: 'Kanada'},
  {code: 'CPV', name: 'Kap Verde'},
  {code: 'KAZ', name: 'Kasachstan'},
  {code: 'QAT', name: 'Katar'},
  {code: 'KEN', name: 'Kenia'},
  {code: 'KGZ', name: 'Kirgisistan'},
  {code: 'KIR', name: 'Kiribati'},
  {code: 'COL', name: 'Kolumbien'},
  {code: 'COM', name: 'Komoren'},
  {code: 'COG', name: 'Kongo'},
  {code: 'COD', name: 'Kongo, Demokratische Republik'},
  {code: 'PRK', name: 'Korea, Demokratische Volksrebuplik'},
  {code: 'KOR', name: 'Korea, Republik'},
  {code: 'XXK', name: 'Kosovo'},
  {code: 'HRV', name: 'Kroatien'},
  {code: 'CUB', name: 'Kuba'},
  {code: 'KWT', name: 'Kuwait'},
  {code: 'LAO', name: 'Laos'},
  {code: 'LSO', name: 'Lesotho'},
  {code: 'LVA', name: 'Lettland'},
  {code: 'LBN', name: 'Libanon'},
  {code: 'LBR', name: 'Liberia'},
  {code: 'LBY', name: 'Libyen'},
  {code: 'LIE', name: 'Liechtenstein'},
  {code: 'LTU', name: 'Litauen'},
  {code: 'LUX', name: 'Luxemburg'},
  {code: 'MDG', name: 'Madagaskar'},
  {code: 'MWI', name: 'Malawi'},
  {code: 'MYS', name: 'Malaysia'},
  {code: 'MDV', name: 'Malediven'},
  {code: 'MLI', name: 'Mali'},
  {code: 'MLT', name: 'Malta'},
  {code: 'MAR', name: 'Marokko'},
  {code: 'MHL', name: 'Marshallinseln'},
  {code: 'MRT', name: 'Mauretanien'},
  {code: 'MUS', name: 'Mauritius'},
  {code: 'MKD', name: 'Mazedonien'},
  {code: 'MEX', name: 'Mexiko'},
  {code: 'FSM', name: 'Mikronesien'},
  {code: 'MDA', name: 'Moldau, Republik'},
  {code: 'MCO', name: 'Monaco'},
  {code: 'MNG', name: 'Mongolei'},
  {code: 'MNE', name: 'Montenegro'},
  {code: 'MOZ', name: 'Mosambik'},
  {code: 'MMR', name: 'Myanmar'},
  {code: 'NAM', name: 'Namibia'},
  {code: 'NRU', name: 'Nauru'},
  {code: 'NPL', name: 'Nepal'},
  {code: 'NZL', name: 'Neuseeland'},
  {code: 'NIC', name: 'Nicaragua'},
  {code: 'NLD', name: 'Niederlande'},
  {code: 'NER', name: 'Niger'},
  {code: 'NGA', name: 'Nigeria'},
  {code: 'NIU', name: 'Niue'},
  {code: 'NOR', name: 'Norwegen'},
  {code: 'OMN', name: 'Oman'},
  {code: 'AUT', name: 'Österreich'},
  {code: 'PAK', name: 'Pakistan'},
  {code: 'PLW', name: 'Palau'},
  {code: 'PAN', name: 'Panama'},
  {code: 'PNG', name: 'Papua-Neuguinea'},
  {code: 'PRY', name: 'Paraguay'},
  {code: 'PER', name: 'Peru'},
  {code: 'PHL', name: 'Philippinen'},
  {code: 'POL', name: 'Polen'},
  {code: 'PRT', name: 'Portugal'},
  {code: 'RWA', name: 'Ruanda'},
  {code: 'ROU', name: 'Rumänien'},
  {code: 'RUS', name: 'Russische Föderation'},
  {code: 'SLB', name: 'Salomonen'},
  {code: 'ZMB', name: 'Sambia'},
  {code: 'WSM', name: 'Samoa'},
  {code: 'SMR', name: 'San Marino'},
  {code: 'SAU', name: 'Saudi-Arabien'},
  {code: 'SWE', name: 'Schweden'},
  {code: 'CHE', name: 'Schweiz'},
  {code: 'SEN', name: 'Senegal'},
  {code: 'SRB', name: 'Serbien'},
  {code: 'SYC', name: 'Seychellen'},
  {code: 'SLE', name: 'Sierra Leone'},
  {code: 'ZWE', name: 'Simbabwe'},
  {code: 'SGP', name: 'Singapur'},
  {code: 'SVK', name: 'Slowakei'},
  {code: 'SVN', name: 'Slowenien'},
  {code: 'SOM', name: 'Somalia'},
  {code: 'ESP', name: 'Spanien'},
  {code: 'LKA', name: 'Sri Lanka'},
  {code: 'LCA', name: 'St. Lucia'},
  {code: 'VCT', name: 'St. Vincent'},
  {code: 'KNA', name: 'St.Kitts, Nevis'},
  {code: 'ZAF', name: 'Südafrika'},
  {code: 'SDN', name: 'Sudan'},
  {code: 'SSD', name: 'Südsudan'},
  {code: 'SUR', name: 'Suriname'},
  {code: 'SWZ', name: 'Swasiland'},
  {code: 'SYR', name: 'Syrien'},
  {code: 'STP', name: 'São Tomé, Príncipe'},
  {code: 'TJK', name: 'Tadschikistan'},
  {code: 'TWN', name: 'Taiwan'},
  {code: 'TZA', name: 'Tansania, Vereinigte Republik'},
  {code: 'THA', name: 'Thailand'},
  {code: 'BES', name: 'The Caribbean Netherlands'},
  {code: 'TLS', name: 'Timor-Leste'},
  {code: 'TGO', name: 'Togo'},
  {code: 'TON', name: 'Tonga'},
  {code: 'TTO', name: 'Trinidad und Tobago'},
  {code: 'TCD', name: 'Tschad'},
  {code: 'CZE', name: 'Tschechische Republik'},
  {code: 'TUN', name: 'Tunesien'},
  {code: 'TUR', name: 'Türkei'},
  {code: 'TKM', name: 'Turkmenistan'},
  {code: 'TUV', name: 'Tuvalu'},
  {code: 'UGA', name: 'Uganda'},
  {code: 'UKR', name: 'Ukraine'},
  {code: 'HUN', name: 'Ungarn'},
  {code: 'URY', name: 'Uruguay'},
  {code: 'UZB', name: 'Usbekistan'},
  {code: 'VUT', name: 'Vanuatu'},
  {code: 'VAT', name: 'Vatikanstadt'},
  {code: 'VEN', name: 'Venezuela'},
  {code: 'ARE', name: 'Vereinigte Arabische Emirate'},
  {code: 'GBR', name: 'Vereinigtes Königreich'},
  {code: 'VNM', name: 'Vietnam'},
  {code: 'CAF', name: 'Zentralafrikanische Republik'},
  {code: 'CYP', name: 'Zypern'}
];
