export enum CountryCode {
  AUT = 'AUT',
  BEL = 'BEL',
  BGR = 'BGR',
  CYP = 'CYP',
  CZE = 'CZE',
  DEU = 'DEU',
  ESP = 'ESP',
  EST = 'EST',
  FRA = 'FRA',
  GRC = 'GRC',
  HRV = 'HRV',
  IRL = 'IRL',
  ITA = 'ITA',
  LTU = 'LTU',
  LUX = 'LUX',
  LVA = 'LVA',
  MLT = 'MLT',
  NLD = 'NLD',
  NOR = 'NOR',
  POL = 'POL',
  PRT = 'PRT',
  SWE = 'SWE',
  SPT = 'SPT',
}
